### ISSUE TITLE
Failing to understand basic usage

### ISSUE THREAD

**Issue by njlr** [ronomon/hash-table#4]
I am trying to create a size-constrained hash set. To model this, I plan to create a hash table where the values are the same as the keys. 

However, I don't think I am using this library properly. 

```javascript
import HashTable from '@ronomon/hash-table';

const table = new HashTable(HashTable.KEY_MAX, HashTable.KEY_MAX, 3, 10);

const key = Buffer.from('abc');

// Add the key
table.cache(key, 0, key, 0);

// Does it exist?
if (table.exist(key, 0)) {
  console.log('hit');
}
```

This code does not print `'hit'`. 

How should I be using this library?

**Comment by jorangreef** [comment]
@njlr, you are telling the hash table instance that your key size is KEY_MAX, i.e. 64 bytes, but then you are only passing a key of 3 bytes.

@ronomon/hash-table uses fixed size keys and fixed size values.

If you specify 64 bytes for the key and value size, then your buffer must be at least that large.

If you fix that, your example should work!
