### ISSUE TITLE
C implementation

### ISSUE THREAD

**Issue by nlescoua** [ronomon/hash-table#5]
Hi,

I just came accross your implementation. By curiosity, were you aware of Cuckoo++ paper ( https://arxiv.org/abs/1712.09624 ) at the time you implemented this ? Note that, later, we have been able to release the C source-code implementation at https://github.com/technicolor-research/cuckoopp . 

Best regards,

**Comment by jorangreef** [comment]
Thanks @nlescoua, that looks fantastic, I will check it out. At the time I actually tried a C implementation with SIMD instructions, but the bridging cost into JavaScript was too high and it was faster to write in JavaScript directly.

**Comment by jtenner** [comment]
A proper hand crafted AssemblyScript version of this software is something on my todo list. I really want leverage Web Assembly. Gives direct access to SIMD too.

I need to read through this myself!
